async function saveSalaryVault(){if(!salaryCryptoKey||!salaryVault)return;const iv=crypto.getRandomValues(new Uint8Array(12)),plain=new TextEncoder().encode(JSON.stringify(salaryVault)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv},salaryCryptoKey,plain);localStorage.setItem(SALARY_KEY,JSON.stringify({iv:bytesToB64(iv),cipher:bytesToB64(cipher)}));persistDesktop()}
async function unlockSalary(password){
 const key=await deriveOwnerKey(password),stored=JSON.parse(localStorage.getItem(SALARY_KEY)||'null');let vault={rates:{},overtime:{}};
 if(stored){const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:b64ToBytes(stored.iv)},key,b64ToBytes(stored.cipher));vault=JSON.parse(new TextDecoder().decode(plain));if(!vault.rates)vault.rates={};if(!vault.overtime)vault.overtime={}}
 salaryCryptoKey=key;salaryVault=vault;bossUnlocked=true;await migratePlainSalary();return true;
}
async function migratePlainSalary(){
 let changed=false;db.employees.forEach(e=>{if(Number.isFinite(+e.hourlyRate)&&+e.hourlyRate>0){salaryVault.rates[e.addedFrom||'2026-09']=salaryVault.rates[e.addedFrom||'2026-09']||{};if(salaryVault.rates[e.addedFrom||'2026-09'][e.id]==null)salaryVault.rates[e.addedFrom||'2026-09'][e.id]=+e.hourlyRate;delete e.hourlyRate;changed=true}});
 Object.entries(db.months).forEach(([key,m])=>Object.entries(m.details||{}).forEach(([id,d])=>{if(Number.isFinite(+d.rate)){salaryVault.rates[key]=salaryVault.rates[key]||{};salaryVault.rates[key][id]=+d.rate;delete d.rate;changed=true}}));
 if(changed)save();await saveSalaryVault();
}
function salaryRate(emp,key=monthKey()){const exact=salaryVault?.rates?.[key]?.[emp.id];if(Number.isFinite(+exact))return+exact;const prior=Object.keys(salaryVault?.rates||{}).filter(k=>k<=key&&Number.isFinite(+salaryVault.rates[k]?.[emp.id])).sort().reverse()[0];return prior?+salaryVault.rates[prior][emp.id]:0}
function overtimeConfig(key=monthKey()){const c=salaryVault?.overtime?.[key]||{};return{weekday:Number.isFinite(+c.weekday)?+c.weekday:1,saturday:Number.isFinite(+c.saturday)?+c.saturday:1,sunday:Number.isFinite(+c.sunday)?+c.sunday:1}}
function overtimeBreakdown(emp,key=monthKey()){const cutoff=removalDay(emp,key),hours=monthData(key).hours[emp.id]||{};let weekdayBase=0,weekdayOt=0,sat=0,sun=0;const y=+key.slice(0,4),m=+key.slice(5,7)-1,count=new Date(y,m+1,0).getDate();for(let d=1;d<=count;d++){if(d>cutoff)break;const v=+hours[d]||0;if(v<=0)continue;const dow=new Date(y,m,d).getDay();if(dow===6)sat+=v;else if(dow===0)sun+=v;else{weekdayBase+=Math.min(v,8);weekdayOt+=Math.max(0,v-8)}}return{weekdayBase,weekdayOt,sat,sun}}
function salaryTotals(emp,key=monthKey()){const t=totals(emp,key),rate=salaryRate(emp,key),cfg=overtimeConfig(key),b=overtimeBreakdown(emp,key),gross=(b.weekdayBase*rate)+(b.weekdayOt*rate*cfg.weekday)+(b.sat*rate*cfg.saturday)+(b.sun*rate*cfg.sunday);return{...t,...b,...cfg,rate,gross,net:gross-t.advance}}
function renderBoss(){
 if(!bossUnlocked)return;const emps=summaryEmployees();const cfg=overtimeConfig();$('#weekdayOtMultiplier').value=cfg.weekday;$('#saturdayMultiplier').value=cfg.saturday;$('#sundayMultiplier').value=cfg.sunday;let all={gross:0,advance:0,net:0};let h='<thead><tr><th>Çalışan</th><th>Toplam Saat</th><th>Hafta İçi Normal</th><th>Hafta İçi 8 Saat Sonrası</th><th>Cumartesi</th><th>Pazar</th><th>Saat Ücreti</th><th>Brüt Maaş</th><th>Avans</th><th>Net Ödeme</th></tr></thead><tbody>';
 emps.forEach(e=>{const t=salaryTotals(e);all.gross+=t.gross;all.advance+=t.advance;all.net+=t.net;h+='<tr><td><button class="employee-link" data-boss-employee="'+e.id+'">'+esc(e.name)+'</button></td><td>'+fmtNum(t.hours)+'</td><td>'+fmtNum(t.weekdayBase)+'</td><td>'+fmtNum(t.weekdayOt)+'</td><td>'+fmtNum(t.sat)+'</td><td>'+fmtNum(t.sun)+'</td><td><input class="salary-input" type="text" inputmode="decimal" autocomplete="off" value="'+(t.rate||'')+'" data-salary-id="'+e.id+'" placeholder="0,00"></td><td class="money">'+fmtMoney(t.gross)+'</td><td>'+fmtMoney(t.advance)+'</td><td class="net">'+fmtMoney(t.net)+'</td></tr>'});
 if(!emps.length)h+='<tr><td class="empty" colspan="10">Maaş hesabı yapılacak çalışan yok.</td></tr>';$('#bossTable').innerHTML=h+'</tbody>';$('#bossCards').innerHTML=[['Brüt Maaş',fmtMoney(all.gross)],['Toplam Avans',fmtMoney(all.advance)],['Net Ödeme',fmtMoney(all.net)]].map(x=>'<div class="card"><small>'+x[0]+'</small><b>'+x[1]+'</b></div>').join('');
}
function accountingDays(emp,key=monthKey()){
 const count=new Date(+key.slice(0,4),+key.slice(5,7),0).getDate(),hours=monthData(key).hours[emp.id]||{},entries=datedEntries(emp,key),rate=salaryRate(emp,key),cfg=overtimeConfig(key),cutoff=removalDay(emp,key),rows=[];
 for(let day=1;day<=count;day++){const iso=key+'-'+String(day).padStart(2,'0'),value=day<=cutoff?(+hours[day]||0):0,dow=new Date(+key.slice(0,4),+key.slice(5,7)-1,day).getDay(),advance=entries.filter(x=>x.type==='advance'&&x.date===iso).reduce((s,x)=>s+(+x.amount||0),0),notes=entries.filter(x=>x.date===iso).map(x=>x.description).filter(Boolean).join(' • '),status=day>cutoff?'Ayrıldı':value>0?'Geldi':'Gelmedi',overtime=(dow!==0&&dow!==6)?Math.max(0,value-8):0,pay=dow===6?value*rate*cfg.saturday:dow===0?value*rate*cfg.sunday:(Math.min(value,8)*rate+Math.max(0,value-8)*rate*cfg.weekday);rows.push({day,iso,hours:value,status,overtime,advance,notes,pay})}return rows;
}
function renderBossEmployeeSummary(id){
 if(!bossUnlocked)return;const emp=db.employees.find(x=>x.id===id);if(!emp)return;const rows=accountingDays(emp),total=salaryTotals(emp),week=['Pazar','Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi'];$('#bossEmployeeTitle').textContent=emp.name+' • '+months[+$('#month').value]+' '+$('#year').value;
 let h='<thead><tr><th>Tarih</th><th>Gün</th><th>Çalışma Saati</th><th>Geldi / Gelmedi</th><th>Günlük Mesai</th><th>Avans</th><th>Özel Açıklamalar</th><th>Günlük Ücret</th></tr></thead><tbody>';rows.forEach(x=>{const d=new Date(x.iso+'T00:00:00');h+='<tr><td>'+formatManualDate(x.iso)+'</td><td>'+week[d.getDay()]+'</td><td><b>'+fmtNum(x.hours)+'</b></td><td class="'+(x.status==='Geldi'?'status-in':'status-out')+'">'+x.status+'</td><td>'+fmtNum(x.overtime)+'</td><td>'+fmtMoney(x.advance)+'</td><td class="note-cell">'+esc(x.notes||'—')+'</td><td class="money">'+fmtMoney(x.pay)+'</td></tr>'});h+='<tr><th colspan="2">AYLIK TOPLAM</th><th>'+fmtNum(total.hours)+' saat</th><th>'+total.days+' gün geldi</th><th>'+fmtNum(total.overtime)+' saat</th><th>'+fmtMoney(total.advance)+'</th><th></th><th>'+fmtMoney(total.gross)+'</th></tr>';$('#bossEmployeeTable').innerHTML=h+'</tbody>';$('#bossEmployeeModal').showModal();
}
function parseManualMoney(value){const raw=String(value).trim().replace(',','.');return/^\d+(?:\.\d{0,2})?$/.test(raw)?+raw:NaN}
function activatePage(id){document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.page===id));document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id))}
function clearBossSession(){bossUnlocked=false;salaryVault=null;salaryCryptoKey=null;$('#bossContent').hidden=true;$('#bossLocked').hidden=false}
function lockBoss(){clearBossSession();activatePage('timesheetPage')}
function setPeriod(year,month){while(month<0){month+=12;year--}while(month>11){month-=12;year++}if(![...$('#year').options].some(o=>+o.value===year))$('#year').add(new Option(year,year));$('#year').value=year;$('#month').value=month;render()}
function createNextMonth(){let year=+$('#year').value,month=+$('#month').value+1;if(month>11){month=0;year++}const key=year+'-'+String(month+1).padStart(2,'0');if(!db.months[key]){db.months[key]={hours:{},details:{}};save()}setPeriod(year,month);toast(months[month]+' '+year+' tablosu açıldı')}
function openDetails(id){const e=db.employees.find(x=>x.id===id);$('#detailEmployeeId').value=id;$('#detailEmployeeName').value=e.name;$('#detailTitle').textContent=e.name+' • '+months[+$('#month').value]+' '+$('#year').value;$('#advanceForm').classList.remove('active');$('#otherForm').classList.remove('active');renderDetailRecords(id);$('#detailModal').showModal()}
function renderDetailRecords(id){const emp=db.employees.find(x=>x.id===id),items=datedEntries(emp);$('#detailRecords').innerHTML=items.length?items.map(x=>'<div class="record"><span class="record-type '+x.type+'">'+(x.type==='advance'?'Avans':'Diğer')+'</span><small>'+esc(x.date.split('-').reverse().join('.'))+'</small><span><b>'+(x.type==='advance'?fmtMoney(x.amount):'Açıklama')+'</b><br><small>'+esc(x.description)+'</small></span><button class="remove" data-record-type="'+x.type+'" data-record-id="'+x.id+'">×</button></div>').join(''):'<div class="empty">Bu ay için avans veya diğer kayıt yok.</div>'}
$('#timesheet').addEventListener('input',e=>{const x=e.target.closest('.hour-input');if(!x)return;const raw=x.value.trim();if(!/^(?:\d{1,2}(?:[.,]\d{0,2})?)?$/.test(raw)){x.value=x.dataset.last||'';return}let value=Number(raw.replace(',','.'));if(raw===''||!Number.isFinite(value)||value<=0){delete hoursFor(x.dataset.id)[x.dataset.day];value=''}else{value=Math.min(24,value);hoursFor(x.dataset.id)[x.dataset.day]=value;if(value===24&&Number(raw.replace(',','.'))>24)x.value='24'}x.dataset.last=x.value;x.className='hour-input '+hourClass(value);save();const emp=db.employees.find(e=>e.id===x.dataset.id),t=totals(emp);$('#total-'+emp.id).textContent=fmtNum(t.hours);$('#days-'+emp.id).textContent=t.days});
$('#timesheet').addEventListener('keydown',e=>{if(e.key!=='Enter'&&!e.key.startsWith('Arrow'))return;const inputs=[...document.querySelectorAll('.hour-input')],i=inputs.indexOf(e.target),cols=daysInMonth();let next=i;if(e.key==='Enter'||e.key==='ArrowRight')next=i+1;if(e.key==='ArrowLeft')next=i-1;if(e.key==='ArrowDown')next=i+cols;if(e.key==='ArrowUp')next=i-cols;if(inputs[next]){e.preventDefault();inputs[next].focus();inputs[next].select()}});
function defaultRemovalDate(){const today=todayLocal(),key=monthKey();return today.slice(0,7)===key?today:key+'-'+String(daysInMonth()).padStart(2,'0')}
function prepareRemove(id){const emp=db.employees.find(x=>x.id===id),date=$('#removeDate');if(!emp)return;$('#removeEmployeeId').value=id;$('#removeEmployeeSelect').value=id;$('#removeMessage').textContent=emp.name+' seçili ayın çalışan listesinden silinecek.';date.min=monthKey()+'-01';date.max=monthKey()+'-'+String(daysInMonth()).padStart(2,'0');setDatePair('removeDate',defaultRemovalDate())}
function openRemove(id){prepareRemove(id);$('#removeModal').showModal()}
function employeeSummaryCsv(id,key=monthKey()){const emp=db.employees.find(x=>x.id===id),t=totals(emp,key),h=monthData(key).hours[id]||{},n=new Date(+key.slice(0,4),+key.slice(5,7),0).getDate(),rows=[['Ay',key],['Çalışan',emp.name],[],['Gün','Çalışma Saati']];for(let d=1;d<=n;d++)rows.push([d,h[d]??'']);rows.push([],['Hafta İçi Saat',t.weekday],['Cumartesi Saat',t.saturday],['Pazar Saat',t.sunday],['Toplam Saat',t.hours],['Çalışılan Gün',t.days],['Toplam Avans',t.advance],[],['Tarihli Kayıtlar']);t.entries.forEach(x=>rows.push([entryText(x)]));return'\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\r\n')}
$('#timesheet').addEventListener('click',e=>{const person=e.target.closest('[data-employee]');if(person)openDetails(person.dataset.employee)});
$('#summary').addEventListener('click',e=>{const person=e.target.closest('[data-employee]');if(person)openDetails(person.dataset.employee)});
function openEditEmployee(id){const emp=db.employees.find(x=>x.id===id);if(!emp)return;$('#editEmployeeId').value=id;$('#editEmployeeName').value=emp.name;$('#editEmployeeModal').showModal();setTimeout(()=>{$('#editEmployeeName').focus();$('#editEmployeeName').select()},0)}
$('#editEmployeeForm').onsubmit=e=>{e.preventDefault();const emp=db.employees.find(x=>x.id===$('#editEmployeeId').value);if(!emp)return;const name=upperName($('#editEmployeeName').value);if(!name)return;emp.name=name;save();$('#editEmployeeModal').close();render();toast('Ad soyad güncellendi')};
$('#addEmployee').onclick=()=>{$('#employeeForm').reset();$('#newStartMonth').value=months[+$('#month').value]+' '+$('#year').value;$('#employeeModal').showModal()};
$('#newName').addEventListener('blur',e=>e.target.value=upperName(e.target.value));$('#editEmployeeName').addEventListener('blur',e=>e.target.value=upperName(e.target.value));
$('#removeEmployeeButton').onclick=()=>{const employees=tableEmployees(),select=$('#removeEmployeeSelect');if(!employees.length){toast('Bu ay silinebilecek çalışan yok');return}select.innerHTML=employees.map(e=>'<option value="'+e.id+'">'+esc(e.name)+'</option>').join('');openRemove(employees[0].id)};
$('#removeEmployeeSelect').onchange=e=>prepareRemove(e.target.value);
$('#employeeForm').onsubmit=e=>{e.preventDefault();db.employees.push({id:'e'+Date.now()+Math.random().toString(16).slice(2),name:upperName($('#newName').value),addedFrom:monthKey()});save();$('#employeeModal').close();render();toast('Çalışan tabloya eklendi')};
$('#removeForm').onsubmit=e=>{e.preventDefault();const emp=db.employees.find(x=>x.id===$('#removeEmployeeId').value),date=readDatePair('removeDate');if(!emp||!date)return;if(!date.startsWith(monthKey())){$('#removeDateText').setCustomValidity('Son çalışma tarihi seçili ay içinde olmalıdır');$('#removeDateText').reportValidity();return}emp.removedFromDate=date;delete emp.removedFrom;save();$('#removeModal').close();render();toast('Çalışan silindi; ay özeti korundu')};
$('#downloadEmployeeSummary').onclick=()=>{const id=$('#removeEmployeeId').value,emp=db.employees.find(x=>x.id===id);if(!emp)return;download(employeeSummaryCsv(id),emp.name.replace(/[^a-zA-Z0-9çğıöşüÇĞİÖŞÜ]+/g,'_')+'_'+monthKey()+'_ozet.csv','text/csv;charset=utf-8');toast('Çalışanın aylık özeti indirildi')};
$('#saveEmployeeName').onclick=()=>{const id=$('#detailEmployeeId').value,emp=db.employees.find(x=>x.id===id);if(!emp)return;const name=$('#detailEmployeeName').value.trim().toLocaleUpperCase('tr-TR');if(!name){toast('Ad Soyad boş olamaz');return}emp.name=name;$('#detailEmployeeName').value=name;$('#detailTitle').textContent=name+' • '+months[+$('#month').value]+' '+$('#year').value;save();render();toast('Ad Soyad güncellendi')};
$('#addAdvanceButton').onclick=()=>{$('#otherForm').classList.remove('active');$('#advanceForm').classList.toggle('active');setDatePair('advanceDate',todayLocal());$('#advanceDescription').focus()};
$('#addOtherButton').onclick=()=>{$('#advanceForm').classList.remove('active');$('#otherForm').classList.toggle('active');setDatePair('otherDate',todayLocal());$('#otherDescription').focus()};
$('#advanceForm').onsubmit=e=>{e.preventDefault();const amount=parseManualMoney($('#advanceAmount').value),date=readDatePair('advanceDate');if(!date)return;if(!Number.isFinite(amount)||amount<=0){$('#advanceAmount').setCustomValidity('Geçerli bir avans tutarı yazın');$('#advanceAmount').reportValidity();return}$('#advanceAmount').setCustomValidity('');const id=$('#detailEmployeeId').value,d=detailFor(id);d.advances.push({id:'a'+Date.now()+Math.random().toString(16).slice(2),date,amount,description:$('#advanceDescription').value.trim()});save();e.target.reset();e.target.classList.remove('active');renderDetailRecords(id);render();toast('Avans kaydedildi')};
$('#otherForm').onsubmit=e=>{e.preventDefault();const date=readDatePair('otherDate');if(!date)return;const id=$('#detailEmployeeId').value,d=detailFor(id);d.others.push({id:'o'+Date.now()+Math.random().toString(16).slice(2),date,description:$('#otherDescription').value.trim()});save();e.target.reset();e.target.classList.remove('active');renderDetailRecords(id);render();toast('Açıklama kaydedildi')};
$('#detailRecords').addEventListener('click',e=>{const b=e.target.closest('[data-record-id]');if(!b)return;const d=detailFor($('#detailEmployeeId').value),list=b.dataset.recordType==='advance'?d.advances:d.others;if(!confirm('Bu kayıt silinsin mi?'))return;const i=list.findIndex(x=>x.id===b.dataset.recordId);if(i>=0)list.splice(i,1);save();renderDetailRecords($('#detailEmployeeId').value);render();toast('Kayıt silindi')});
$('#openBossLogin').onclick=()=>{$('#bossLoginForm').reset();$('#bossLoginError').textContent='';$('#bossLoginModal').showModal();setTimeout(()=>$('#bossPassword').focus(),0)};
$('#bossLoginForm').onsubmit=async e=>{e.preventDefault();const error=$('#bossLoginError');error.textContent='Kontrol ediliyor…';try{await unlockSalary($('#bossPassword').value);error.textContent='';$('#bossLoginModal').close();$('#bossLocked').hidden=true;$('#bossContent').hidden=false;activatePage('bossPage');renderBoss();toast('Maaş sayfası açıldı')}catch(err){salaryCryptoKey=null;salaryVault=null;bossUnlocked=false;error.textContent='Şifre yanlış.';$('#bossPassword').select()}};
$('#bossTable').addEventListener('change',async e=>{const input=e.target.closest('[data-salary-id]');if(!input||!bossUnlocked)return;const rate=parseManualMoney(input.value);if(!Number.isFinite(rate)||rate<0){input.setCustomValidity('Geçerli bir saat ücreti yazın');input.reportValidity();return}input.setCustomValidity('');salaryVault.rates[monthKey()]=salaryVault.rates[monthKey()]||{};salaryVault.rates[monthKey()][input.dataset.salaryId]=rate;await saveSalaryVault();renderBoss();toast('Saat ücreti şifreli kaydedildi')});
$('#bossTable').addEventListener('click',e=>{const person=e.target.closest('[data-boss-employee]');if(person&&bossUnlocked)renderBossEmployeeSummary(person.dataset.bossEmployee)});
['weekdayOtMultiplier','saturdayMultiplier','sundayMultiplier'].forEach(id=>$('#'+id).addEventListener('change',async()=>{if(!bossUnlocked)return;const map={weekdayOtMultiplier:'weekday',saturdayMultiplier:'saturday',sundayMultiplier:'sunday'},v=parseManualMoney($('#'+id).value);if(!Number.isFinite(v)||v<0){$('#'+id).setCustomValidity('Geçerli bir katsayı yazın');$('#'+id).reportValidity();return}$('#'+id).setCustomValidity('');salaryVault.overtime=salaryVault.overtime||{};salaryVault.overtime[monthKey()]=salaryVault.overtime[monthKey()]||{};salaryVault.overtime[monthKey()][map[id]]=v;await saveSalaryVault();renderBoss();toast('Mesai katsayısı kaydedildi')}));
$('#lockBoss').onclick=lockBoss;
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{if(b.dataset.page==='bossPage'&&!bossUnlocked){$('#openBossLogin').click();return}if(b.dataset.page!=='bossPage'&&bossUnlocked)clearBossSession();activatePage(b.dataset.page);if(b.dataset.page==='summaryPage')renderSummary();if(b.dataset.page==='bossPage')renderBoss()});
$('#month').onchange=$('#year').onchange=render;$('#prevMonth').onclick=()=>setPeriod(+$('#year').value,+$('#month').value-1);$('#nextMonth').onclick=()=>setPeriod(+$('#year').value,+$('#month').value+1);$('#newMonth').onclick=createNextMonth;
$('#exportCsv').onclick=()=>{const n=daysInMonth(),rows=[['Ay','Çalışan',...Array.from({length:n},(_,i)=>i+1),'Hafta İçi Saat','Cumartesi Saat','Pazar Saat','Toplam Saat','Çalışılan Gün','Toplam Avans','Tarihli Kayıtlar']];summaryEmployees().forEach(e=>{const t=totals(e),h=hoursFor(e.id),cutoff=removalDay(e);rows.push([monthKey(),e.name,...Array.from({length:n},(_,i)=>i+1<=cutoff?h[i+1]??'':''),t.weekday,t.saturday,t.sunday,t.hours,t.days,t.advance,t.note])});const csv='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(';')).join('\r\n');download(csv,'bar_puantaj_'+monthKey()+'.csv','text/csv;charset=utf-8');toast('Excel dosyası indirildi')};
function download(content,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function toast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1500)}
['advanceDate','otherDate','removeDate'].forEach(bindDatePair);
render();
